# Read the Docs configuration file
# See https://2025-ai-gait-identification.readthedocs.io/en/latest/ for details
# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt

